name: Security Check

on:
  pull_request:
  push:

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Security Checker
        uses: symfonycorp/security-checker-action@v5
